device:
  name: apollo
  vendor: nokia

platform:
  product_makefile: device/nokia/apollo/altos_apollo.mk

  sepolicy_dirs:
    - device/qcom/sepolicy_vndr
    - device/qcom/sepolicy

includes:
  - snippets/hmd.yml
  - snippets/qcom.yml
  - ../snippets/mainline_system.yml
  - ../snippets/gms.yml

filters:
  dep_files:
    match:
      - vendor/etc/vintf/manifest/android.hardware.graphics.mapper-impl-qti-display.xml
      - vendor/etc/vintf/manifest/power.xml
      - vendor/etc/vintf/manifest/vendor.qti.hardware.display.allocator-service.xml
      - vendor/etc/vintf/manifest/vendor.qti.hardware.display.composer-service.xml

  files:
    match:
      - product/app/WallpaperPicker_apo/WallpaperPicker_apo.apk
      - system_ext/app/GmsSampleIntegration_apo/GmsSampleIntegration_apo.apk
