device:
  name: falcon
  vendor: nokia

platform:
  product_makefile: device/nokia/falcon/full_falcon.mk

  sepolicy_dirs:
    - device/qcom/sepolicy

includes:
  - ../snippets/mainline_system.yml
  - ../snippets/gms.yml

filters:
  files:
    prefix:
      # We don't want to include anything from /system as this is a mainline platform
      - system/
      - vendor/lib/vndk/
      # We use a vendor snapshot so ignore everything in vendor and odm
      - vendor/
      - odm/

    match:
      - system_ext/app/GmsSampleIntegration_fcn/GmsSampleIntegration_fcn.apk

  overlay_keys:
    prefix:
      - com.hmdglobal.app.activation

  overlay_values:
    substring:
      - com.google.android.ext.services
      - com.hmdglobal.app.activation

  overlay_files:
    match:
      - GmsResourceOverlayVelvet.apk
