device:
  name: zx10
  vendor: getac

platform:
  product_makefile: device/getac/zx10/altos_zx10.mk

includes:
  - ../snippets/mainline_system.yml
  - ../snippets/gms.yml
  - snippets/qcom.yml

filters:
  dep_files:
    match:
      - vendor/etc/vintf/manifest/vendor.qti.hardware.display.allocator-service.xml
      - vendor/etc/vintf/manifest/android.hardware.graphics.mapper-impl-qti-display.xml
      - vendor/etc/vintf/manifest/power.xml

  files:
    match:
      - product/app/GmsSampleIntegration/GmsSampleIntegration.apk
      - system_ext/priv-app/GoogleOneTimeInitializer/GoogleOneTimeInitializer.apk
      - vendor/app/app-camera/app-camera.apk
      - vendor/app/app-deploy-center/app-deploy-center.apk
      - vendor/app/app-device-manual/app-device-manual.apk
      - vendor/app/app-getac-drivesafety/app-getac-drivesafety.apk
      - vendor/app/app-getac-ime/app-getac-ime.apk
      - vendor/app/app-getac-settings/app-getac-settings.apk
      - vendor/app/app-update-center/app-update-center.apk
      - vendor/bin/hw/vendor.getac.gasp@1.0-service
      - vendor/etc/init/vendor.getac.gasp@1.0-service.rc
      - vendor/lib64/vendor.getac.gasp@1.0.so

    prefix:
      - vendor/app/DisplayLinkPresenter/
      - vendor/lib/vndk/
      - vendor/odm

  props:
    match:
      - ro.nfc.port
      - ro.product.cpu.abilist
      - ro.product.cpu.abilist32
      - ro.product.cpu.abilist64
