includes:
  - common.yml

platform:
  sepolicy_dirs:
    - device/google/gs-common/wireless_charger/sepolicy

filters:
  partitions:
    match:
      # AOSP doesn't build chained vendor vbmeta by default
      - vbmeta_vendor

      # TODO: add support for OTA firmware partitions
      - bl1
      - pbl
      - bl2
      - abl
      - bl31
      - tzsw
      - gcf
      - gsa_bl1
      - gsa
      - ldfw
      - modem
