includes:
  - common.yml

filters:
  partitions:
    match:
      # AOSP doesn't build chained vendor vbmeta by default
      - vbmeta_vendor

      # TODO: add support for OTA firmware partitions
      - bl1
      - pbl
      - bl2
      - abl
      - bl31
      - tzsw
      - gsa
      - ldfw
      - modem
