device:
  name: sunfish

platform:
  product_makefile: device/google/sunfish/aosp_sunfish.mk

  sepolicy_dirs:
    - device/google/sunfish-sepolicy

includes:
  - snippets/common.yml

filters:
  partitions:
    match:
      # TODO: add support for OTA firmware partitions
      - abl
      - aop
      - devcfg
      - hyp
      - keymaster
      - modem
      - qupfw
      - tz
      - uefisecapp
      - xbl
      - xbl_config

  dep_files:
    match:
      # Required by libOmxSwVencMpeg4
      - vendor/lib/libMpeg4SwEncoder.so
      - vendor/lib64/libMpeg4SwEncoder.so

      # Required by vendor.qti.hardware.display.composer-service
      - vendor/lib64/libthermalclient.so

      # Required by chre
      - vendor/lib/libadsprpc.so
      - vendor/lib64/libadsprpc.so

      # Required by libOmxVenc
      - vendor/lib/libfastcvopt.so
      - vendor/lib64/libfastcvopt.so

      # Needed to pass checkvintf
      - vendor/etc/vintf/manifest/android.hardware.graphics.mapper-impl-qti-display.xml
      - vendor/etc/vintf/manifest/c2_manifest_vendor.xml
      - vendor/etc/vintf/manifest/pixel-display-default.xml
      - vendor/etc/vintf/manifest/vendor.qti.hardware.display.allocator-service.xml
      - vendor/etc/vintf/manifest/vendor.qti.hardware.display.composer-service.xml
