filters:
  files:
    prefix:
      # Fonts and media in system partitions
      - system/fonts/
      - system/media/
      - system_ext/fonts/
      - system_ext/media/
      - product/fonts/
      - product/etc/fonts_customization.xml
      - product/media/
      # Fonts in vendor. On Pixel devices, important camera/face unlock files are in /vendor/media.
      - vendor/fonts/

      # Overlays are created separately and should never be copied as APKs.
      - system/overlay/
      - system_ext/overlay/
      - product/overlay/
      - vendor/overlay/

      # Kernel modules should be built from source or AOSP prebuilts, not copied from stock.
      - vendor/lib/modules
      - vendor/vendor_dlkm
      - vendor_dlkm/
      - odm/lib/modules
      - odm_dlkm/

    suffix:
      # Compiled app code and profiles
      - .art
      - .odex
      - .vdex
      - .prof

  props:
    match:
      # Debug
      - ro.adb.secure

      # Sound
      - ro.config.alarm_alert
      - ro.config.notification_sound
      - ro.config.ringtone
