filters:
  props:
    match:
      # GMS
      - ro.opa.eligible_device
      - ro.atrace.core.services
      - ro.com.google.clientidbase
      - ro.error.receiver.system.apps
      - ro.com.google.gmsversion

    prefix:
      # Gboard
      - ro.com.google.ime.
      - ro.storage_manager.

  files:
    match:
      - product/app/arcore/arcore.apk
      - product/app/CalculatorGooglePrebuilt/CalculatorGooglePrebuilt.apk
      - product/app/CalculatorGoogle/CalculatorGoogle.apk
      - product/app/CalendarGooglePrebuilt/CalendarGooglePrebuilt.apk
      - product/app/CalendarGoogle/CalendarGoogle.apk
      - product/app/Chrome-Stub/Chrome-Stub.apk
      - product/app/Chrome/Chrome.apk.gz
      - product/app/Chrome/Chrome.apk
      - product/app/DeskClockGoogle/DeskClockGoogle.apk
      - product/app/Drive/Drive.apk
      - product/app/Gmail2/Gmail2.apk
      - product/app/GoogleContacts/GoogleContacts.apk
      - product/app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk
      - product/app/GoogleLocationHistory/GoogleLocationHistory.apk
      - product/app/GoogleTTS/GoogleTTS.apk
      - product/app/Keep/Keep.apk
      - product/app/LatinIMEGooglePrebuilt/LatinIMEGooglePrebuilt.apk
      - product/app/LatinImeGoogle/LatinImeGoogle.apk
      - product/app/LocationHistoryPrebuilt/LocationHistoryPrebuilt.apk
      - product/app/Maps/Maps.apk
      - product/app/ModuleMetadataGoogle/ModuleMetadataGoogle.apk
      - product/app/Photos/Photos.apk
      - product/app/PlayAutoInstallConfig/PlayAutoInstallConfig.apk
      - product/app/PrebuiltDeskClockGoogle/PrebuiltDeskClockGoogle.apk
      - product/app/PrebuiltGmail/PrebuiltGmail.apk
      - product/app/SpeechServicesByGoogle/SpeechServicesByGoogle.apk
      - product/app/talkback/talkback.apk
      - product/app/TrichromeLibrary-Stub/TrichromeLibrary-Stub.apk
      - product/app/TrichromeLibrary/TrichromeLibrary.apk.gz
      - product/app/TrichromeLibrary/TrichromeLibrary.apk
      - product/app/Tycho/Tycho.apk
      - product/app/Videos/Videos.apk
      - product/app/WebViewGoogle-Stub/WebViewGoogle-Stub.apk
      - product/app/WebViewGoogle/WebViewGoogle.apk.gz
      - product/app/WebViewGoogle/WebViewGoogle.apk
      - product/app/YouTube/YouTube.apk
      - product/app/YouTubeMusicPrebuilt/YouTubeMusicPrebuilt.apk
      - product/app/com.google.android.modulemetadata/com.google.android.modulemetadata.apk
      - product/app/com.google.mainline.adservices/com.google.mainline.adservices.apk
      - product/app/com.google.mainline.telemetry/com.google.mainline.telemetry.apk
      - product/etc/permissions/split-permissions-google.xml
      - product/etc/preferred-apps/google.xml
      - product/etc/sysconfig/google-staged-installer-whitelist.xml
      - product/framework/com.google.android.dialer.support.jar
      - product/priv-app/AndroidAutoStubPrebuilt/AndroidAutoStubPrebuilt.apk
      - product/priv-app/AndroidAutoStub/AndroidAutoStub.apk
      - product/priv-app/AssistantShell/AssistantShell.apk
      - product/priv-app/CarrierServices/CarrierServices.apk
      - product/priv-app/ConfigUpdater/ConfigUpdater.apk
      - product/priv-app/FilesGoogle/FilesGoogle.apk
      - product/priv-app/FilesPrebuilt/FilesPrebuilt.apk
      - product/priv-app/GCS/GCS.apk
      - product/priv-app/GmsCore/GmsCore.apk
      - product/priv-app/GmsCore/m/independent/AndroidPlatformServices.apk
      - product/priv-app/GoogleDialer/GoogleDialer.apk
      - product/priv-app/GoogleOneTimeInitializer/GoogleOneTimeInitializer.apk
      - product/priv-app/GooglePartnerSetup/GooglePartnerSetup.apk
      - product/priv-app/GoogleRestorePrebuilt/GoogleRestorePrebuilt.apk
      - product/priv-app/GoogleRestore/GoogleRestore.apk
      - product/priv-app/Messages/Messages.apk
      - product/priv-app/PartnerSetupPrebuilt/PartnerSetupPrebuilt.apk
      - product/priv-app/Phonesky/Phonesky.apk
      - product/priv-app/PrebuiltBugle/PrebuiltBugle.apk
      - product/priv-app/RecorderPrebuilt/RecorderPrebuilt.apk
      - product/priv-app/SetupWizardPrebuilt/SetupWizardPrebuilt.apk
      - product/priv-app/SetupWizard/SetupWizard.apk
      - product/priv-app/Turbo/Turbo.apk
      - product/priv-app/Velvet/Velvet.apk
      - product/priv-app/WellbeingPrebuilt/WellbeingPrebuilt.apk
      - product/priv-app/Wellbeing/Wellbeing.apk
      - system_ext/priv-app/GoogleFeedback/GoogleFeedback.apk
      - system_ext/priv-app/GoogleServicesFramework/GoogleServicesFramework.apk
      - system_ext/priv-app/SetupWizard/SetupWizard.apk
      - system/etc/permissions/privapp-permissions-google.xml

    prefix:
      - product/etc/sysconfig/preinstalled-packages-
      - product/priv-app/PrebuiltGmsCore/
      - product/usr/share/ime/google/
      - product/usr/srec/
      - system_ext/priv-app/SearchLauncher

  overlay_files:
    match:
      - GmsResourceOverlayVelvet.apk

  overlay_keys:
    match:
      - android:string/config_defaultCaptivePortalLoginPackageName
      - android:string/config_defaultSms
      - android:string/config_systemContacts
      - android:string/config_incidentReportApproverPackage
      - android:string/config_defaultModuleMetadataProvider

  overlay_values:
    substring:
      - com.google.android.ext.services
      - com.google.android.gms
      - com.google.android.dialer
