includes:
  - base.yml

filters:
  files:
    match:
      - system/apex/com.google.mainline.primary.libs.apex
      - system/app/GoogleExtShared/GoogleExtShared.apk
      - system/app/GooglePrintRecommendationService/GooglePrintRecommendationService.apk
      - system/priv-app/GooglePackageInstaller/GooglePackageInstaller.apk
      - system/priv-app/TagGoogle/TagGoogle.apk

    prefix:
      - system/apex/
      - system_ext/apex/
      - system/app/CaptivePortalLoginGoogle/
      - system/priv-app/DocumentsUIGoogle/
      - system/priv-app/NetworkPermissionConfigGoogle/
      - system/priv-app/NetworkStackGoogle/
